Repository AlberdaNazarius/StudlessApp, pull requests merged in 2023-11, with the labels that each got.

#13 Fixed header
  src/app/app.component.html
  src/app/app.component.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.ts
  src/assets/images/profile-logo.png
  src/styles.scss
Labels: fix

#14 MES-10 Add question detail component
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/home/home.component.ts
  src/app/home/topic-panel/topic-panel.component.ts
  src/app/question-detail/detail-block/detail-block.component.html
  src/app/question-detail/detail-block/detail-block.component.scss
  src/app/question-detail/detail-block/detail-block.component.ts
  src/app/question-detail/detail-block/user-info/user-info.component.html
  src/app/question-detail/detail-block/user-info/user-info.component.scss
  src/app/question-detail/detail-block/user-info/user-info.component.ts
  src/app/question-detail/question-detail.component.html
  src/app/question-detail/question-detail.component.scss
  src/app/question-detail/question-detail.component.ts
  src/app/question-list/question/question.component.html
  src/app/shared/models/answer-model.ts
  src/app/shared/models/question.model.ts
  src/app/shared/services/question.service.ts
Labels: enhancement, fix

#15 Improved question-detail and search result components design
  src/app/question-detail/question-detail.component.html
  src/app/question-detail/question-detail.component.scss
  src/app/question-list/question-list.component.html
  src/app/question-list/question-list.component.scss
Labels: enhancement

#17 Add custom text pipeline
  src/app/app.module.ts
  src/app/home/topic-panel/topic-panel.component.html
  src/app/question-detail/question-detail.component.html
  src/app/question-list/question/question.component.html
  src/app/shared/components/compact-question/compact-question.component.html
  src/app/shared/pipes/slice-and-dots.pipe.ts
  src/app/shared/services/question.service.ts
Labels: fix

#19 Add routing
  src/app/app-routing.module.ts
  src/app/header/header.component.html
  src/app/header/header.component.ts
  src/app/profile/profile.component.ts
  src/app/question-detail/question-detail.component.html
  src/app/question-detail/question-detail.component.ts
  src/app/question-list/question-list.component.html
  src/app/question-list/question-list.component.ts
  src/app/question-list/question/question.component.html
  src/app/shared/components/compact-question/compact-question.component.html
  src/app/shared/services/question.service.ts
  src/app/shared/services/user.service.ts
Labels: enhancement

#20 Removed files
  src/assets/HomePage/images/avatar.jpg
  src/assets/HomePage/images/logo.png
  src/assets/HomePage/main.html
  src/assets/HomePage/styles/general.css
  src/assets/HomePage/styles/header_style.css
  src/assets/HomePage/styles/home_page.css
  src/assets/LoginPage/images/google.png
  src/assets/LoginPage/images/logo.png
  src/assets/LoginPage/main.html
  src/assets/LoginPage/styles/general.css
  src/assets/LoginPage/styles/header_style.css
  src/assets/LoginPage/styles/login_style.css
  src/assets/QuestionPage/images/ecab07c30e5388da23e4dc6cff4cb258.png
  src/assets/QuestionPage/images/logo.png
  src/assets/QuestionPage/images/table.png
  src/assets/QuestionPage/main.html
  src/assets/QuestionPage/styles/general.css
  src/assets/QuestionPage/styles/header_style.css
  src/assets/QuestionPage/styles/question_page_style.css
  src/assets/SearchResultPage/images/ecab07c30e5388da23e4dc6cff4cb258.png
  src/assets/SearchResultPage/main.html
  src/assets/SearchResultPage/styles/general.css
  src/assets/SearchResultPage/styles/header_style.css
  src/assets/SearchResultPage/styles/main_page.css
  src/assets/SignUpPage/images/google.png
  src/assets/SignUpPage/images/logo.png
  src/assets/SignUpPage/main.html
  src/assets/SignUpPage/styles/general.css
  src/assets/SignUpPage/styles/header_style.css
  src/assets/SignUpPage/styles/sign_up_page.css
  src/assets/User Page/images/avatar.jpg
  src/assets/User Page/images/logo.png
  src/assets/User Page/images/user-background.png
  src/assets/User Page/main.html
  src/assets/User Page/styles/general.css
  src/assets/User Page/styles/header_style.css
  src/assets/User Page/styles/user_style.css
Labels: fix

#21 Added rating buttons events
  src/app/question-detail/detail-block/detail-block.component.html
  src/app/question-detail/detail-block/detail-block.component.ts
Labels: enhancement

#22 Pagination
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/question-detail/detail-block/user-info/user-info.component.html
  src/app/question-list/question-list.component.html
  src/app/question-list/question-list.component.ts
  src/app/shared/components/paginator/paginator.component.html
  src/app/shared/components/paginator/paginator.component.scss
  src/app/shared/components/paginator/paginator.component.ts
  src/app/shared/services/paginator.service.ts
Labels: enhancement

#23 Added AuthService, interceptors and route guard
  package-lock.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/shared/guards/auth.guard.ts
  src/app/shared/services/auth-expired-interceptor.service.ts
  src/app/shared/services/auth-interceptor.service.ts
  src/app/shared/services/auth.service.ts
  src/app/shared/utils/auth-data-utils.ts
Labels: enhancement

#24 Create sign up component
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.ts
  src/app/shared/guards/auth.guard.ts
  src/app/shared/services/question.service.ts
  src/app/shared/services/user.service.ts
  src/app/shared/utils/auth-data-utils.ts
  src/app/sign-up/sign-up.component.html
  src/app/sign-up/sign-up.component.scss
  src/app/sign-up/sign-up.component.ts
Labels: enhancement

#26 Create Login component
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/login/login.component.html
  src/app/auth/login/login.component.scss
  src/app/auth/login/login.component.ts
  src/app/header/header.component.html
  src/app/profile/compact-answer/compact-answer.component.html
  src/app/profile/compact-answer/compact-answer.component.scss
  src/app/profile/compact-answer/compact-answer.component.ts
  src/app/profile/profile-question/profile-question.component.html
  src/app/profile/profile-question/profile-question.component.scss
  src/app/profile/profile.component.html
  src/app/profile/profile.component.ts
  src/app/shared/services/question.service.ts
  src/app/shared/utils/sort-utils.ts
  src/index.html
Labels: enhancement
